<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="room.xsl"?>
<!DOCTYPE rooms[
        <!ELEMENT rooms (position,a:room+,script)>
        <!ELEMENT position EMPTY>
        <!ELEMENT a:room (member+)>
        <!ELEMENT script (#PCDATA)>
        <!ELEMENT member (age,height,weight)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT height (#PCDATA)>
        <!ELEMENT weight (#PCDATA)>
        <!ATTLIST a:room code ID "113">
        <!ATTLIST member name ID "113">
        <!ATTLIST position address CDATA "C4">
        ]>
<!--begin xml file for test &lt;entity test$gt; 注释中的实体并不会被展开-->
<rooms xmlns="http://lonufate.git.io" xmlns:a="http://geronimo.apache.org/xml/ns/attributes">
    where we live &gt;entity test&lt; <!--entity in node text-->
    <position address="ISS C4"/>
    <a:room code="113">
        <member name="Nero">
            <age>18<?xml-stylesheet type="text/xsl" href="room.xsl"?></age>
            <height>172cm</height>
            <weight>60kg</weight>
        </member>
        <member name="Oliver">
            <age>18</age>
            <height>170cm</height>
            <weight>63kg</weight>
        </member>
        <member name="Jared" xmlns="http://java.sun.com/xml/ns/j2ee">
            <age>18</age>
            <height>175cm</height>
            <weight xmlns="http://cxf.apache.org/jaxws">65kg</weight>
        </member>
        <member name="Maple" xmlns="http://java.sun.com/xml/ns/j2ee">
            <age>18</age>
            <height>176cm</height>
            <weight>70kg</weight>
        </member>
    </a:room>
    <script><![CDATA[
function matchwo(a,b)
{
if (a < b && a < 0) then
  {
  return 1;
  }
else
  {
  return 0;
  }
}
]]></script>
</rooms>
        <!--end-->